version: 5.1.0
variant: default
logo: /images/logos/1x/banner_center.png
head:
    favicon: /images/logos/icon_square.svg
    manifest:
        name: Abyssers' Blog
        short_name: null
        start_url: null
        theme_color: "#1c085d"
        background_color: null
        display: standalone
        icons:
            - src: ""
              sizes: ""
              type: null
    open_graph:
        title: null
        type: blog
        url: null
        image: null
        site_name: null
        author: null
        description: null
        twitter_card: null
        twitter_id: null
        twitter_site: null
        google_plus: null
        fb_admins: null
        fb_app_id: null
    structured_data:
        title: null
        description: null
        url: null
        author: null
        publisher: null
        publisher_logo: null
        image: null
    meta:
        - ""
    rss: null
navbar:
    menu:
        Home: /
        Archives: /archives
        Categories: /categories
        Tags: /tags
        About: /about
    links:
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/Abyssers/blog
footer:
    links:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution 4.0 International:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Download on GitHub:
            icon: fab fa-github
            url: https://github.com/Abyssers/blog
article:
    highlight:
        theme: atom-one-light
        clipboard: true
        fold: unfolded
    readtime: true
    update_time: true
    licenses:
        Creative Commons:
            icon: fab fa-creative-commons
            url: https://creativecommons.org/
        Attribution:
            icon: fab fa-creative-commons-by
            url: https://creativecommons.org/licenses/by/4.0/
        Noncommercial:
            icon: fab fa-creative-commons-nc
            url: https://creativecommons.org/licenses/by-nc/4.0/
search:
    type: insight
comment:
    type: utterances
    repo: Abyssers/abyssers.github.io
    issue_term: pathname
    label: comment
    theme: github-light
donates:
    - type: afdian
      url: ""
    - type: alipay
      qrcode: ""
    - type: buymeacoffee
      url: ""
    - type: patreon
      url: ""
    - type: wechat
      qrcode: ""
share:
    type: addtoany
sidebar:
    left:
        sticky: false
    right:
        sticky: false
widgets:
    - position: left
      type: profile
      author: Abyssers
      author_title: Believe in the abyss!
      location: China
      contributors:
          - name: Morilence
            avatar: https://avatars.githubusercontent.com/u/44861693
            link: https://github.com/Morilence
            contributions: 229
          - name: GarlicGo
            avatar: https://avatars.githubusercontent.com/u/50868054
            link: https://www.garlicgo.com/
            contributions: 19
          - name: Ghoster
            avatar: https://avatars.githubusercontent.com/u/43604079
            link: https://github.com/Ghoster-l
            contributions: 1
      avatar: /images/logos/2x/icon_center.png
      avatar_rounded: false
      gravatar: null
      follow_link: https://github.com/Abyssers
      social_links:
          Github:
              icon: fab fa-github
              url: https://github.com/Abyssers
          Facebook:
              icon: fab fa-facebook
              url: https://facebook.com
          Twitter:
              icon: fab fa-twitter
              url: https://twitter.com
          Dribbble:
              icon: fab fa-dribbble
              url: https://dribbble.com
          RSS:
              icon: fas fa-rss
              url: /
    - position: left
      type: categories
    - position: left
      type: tags
      order_by: name
      amount: null
      show_count: true
    - position: left
      type: followit
      description: null
      action_url: ""
      verification_code: ""
    - position: left
      type: links
      links:
          Hexo: https://hexo.io
          Bulma: https://bulma.io
    - position: right
      type: recent_posts
    - position: right
      type: archives
    - position: right
      type: adsense
      client_id: ""
      slot_id: ""
plugins:
    animejs: true
    back_to_top: true
    baidu_analytics:
        tracking_id: null
    bing_webmaster:
        tracking_id: 9C83E34B0CD78C24C94AAB9E3A2D49B7
    busuanzi: false
    cnzz:
        id: null
        web_id: null
    cookie_consent:
        type: info
        theme: edgeless
        static: false
        position: bottom-left
        policyLink: https://www.cookiesandyou.com/
    gallery: true
    google_analytics:
        tracking_id: null
    hotjar:
        site_id: null
    katex: true
    mathjax: false
    outdated_browser: false
    progressbar: true
    statcounter:
        project: null
        security: null
    twitter_conversion_tracking:
        pixel_id: null
providers:
    cdn: jsdelivr
    fontcdn: google
    iconcdn: fontawesome
